config/routes.rb
TropoExample::Application.routes.draw do

  root :to => "main#make_call"
  
  match '/make_call' => "main#make_call"
  match '/handle_calls' => "main#handle_calls"
  match '/speak/:message' => "main#speak", :as => :speak
  match '/hangup' =>"main#hangup"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
    require 'tropo-webapi-ruby'
    require 'net/http' 
    require 'uri'
  
  def make_call
    
    if request.post?
         @my_tropo_token = "PLACE YOUR TOKEN HERE"
         @API_URL='http://api.tropo.com/1.0/sessions?action=create&' 
         Net::HTTP.get_print URI.parse(URI.encode(@API_URL+'&token='+@my_tropo_token+'&number_to_dial='+params[:call][:number]+"&message="+params[:call][:message]+'&from_number='+params[:call][:from])) 
         redirect_to root_path
    end
  end
    
  
  def handle_calls # this is the URL placed in your TROPO account for handling voice calls. 
    tropo_session = Tropo::Generator.parse(request.env["rack.input"].read)
     puts tropo_session # Helps you see the paramaters passed back. You can pass anything to help redirect to the proper method (ie. emergency, normal call, etc)         
          tropo = Tropo::Generator.new do
            #on :event => 'hangup', :next => '/hangup.json'
            message = tropo_session['session']['parameters']['message']
            url = URI.encode("/speak/#{message}")
            on :event => 'continue', :next => url
            call(:to=>"tel:+1" + tropo_session['session']['parameters']['number_to_dial'],:from => tropo_session['session']['parameters']['from_number'])     
          end
          render :json => tropo
  end
  
  def speak
    message_to_deliver = params[:message]
     puts "Message:#{message_to_deliver}" 
     sleep 1
     tropo = Tropo::Generator.new do
       on :event => 'continue', :next => '/hangup'
       say "#{message_to_deliver}", :voice => 'allison'
     end
     render :json => tropo
    
  end
  
  def hangup
     json_string = request.env["rack.input"].read
     tropo_session = Tropo::Generator.parse json_string
     puts tropo_session 
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_flash(flash)
    ret = []
    flash.each do |name, msg|
      ret << content_tag(:div, msg, :id => "flash_#{name}")
    end
    ret
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TropoExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <%= display_flash(flash) %>
<div id="content">
<%= yield %>
</div>

</body>
</html>

app/views/main/make_call.html.erb
<h1>Make a Call</h1>
<%= form_tag make_call_path, :method => :post do %>
	<table>
		<tr>
			<td>Dial#:</td><td><%= text_field :call, :number %></td>
		</tr>
		<tr>
			<td>From#:</td><td><%= text_field :call, :from %> <em style="font-size:10px">(leave blank for 'unavailable' number)</em></td>
		</tr>
		<tr>
			<td>Message:</td><td><%= text_area :call, :message, :size => "50x10" %></td>
	  </tr>
	</table>
	<br/>
	<%= submit_tag "Make Call"%>
<% end %>